### PR TITLE
upload to ubuntu , live to AWS

### PR DESCRIPTION
**Pull request by rreuptomoon**
老師請您查看看
我的網址是:
http://13.251.71.73:3000/api/attractions/1

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://13.251.71.73:3000/api/attractions?page=4 is incorrect.
2. `"null"` is not `null`.
3. `images` field of attraction should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`
4. http://13.251.71.73:3000/api/categories does not work.

Solve issues and re-request review.

**Comment by rreuptomoon** [comment]
> 1. Response format of http://13.251.71.73:3000/api/attractions?page=4 is incorrect.
format is point to what format >? 
sorry ..can you explain more pls!

**Comment by cwpeng** [comment]
Just compare your response data with API specification. Structure hirarchy, column names, etc...

**Comment by rreuptomoon** [comment]
specification. Structure hirarchy, column names, etc...
image
Must follow same like this ?

**Comment by cwpeng** [comment]
Why you think we don't need to follow API specification?

**Comment by rreuptomoon** [comment]
Because I ask you before in dc

老師，我想問json 資料順序排列次序跟你不一樣有沒有關係？

So i misunderstanding .....

**Comment by cwpeng** [comment]
Ordering of key-value pairs can be arbitrary.

**Comment by rreuptomoon** [comment]
@cwpeng  please review 
page: http://13.251.71.73:3000/api/attractions?page=0
id : http://13.251.71.73:3000/api/attractions/1
cat : http://13.251.71.73:3000/api/categories/
thank you !!

**Comment by rreuptomoon** [comment]
@cwpeng please review
page: http://13.251.71.73:3000/api/attractions?page=0
id : http://13.251.71.73:3000/api/attractions/1
cat : http://13.251.71.73:3000/api/categories
thank you !!

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Every attraction should contains 1 or more images.
2. Response format of your APIs are incorrect.
3. You have not implement keyword search API. For example: http://13.251.71.73:3000/api/attractions?page=3&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80 should response attractions with category is 藝文館所

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almose done but response of http://13.251.71.73:3000/api/categories should be an 1 dimension array containing category names.

**Comment by rreuptomoon** [comment]
thank you !! @cwpeng

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
